EMS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('signup.urls', namespace='signup')),
    path('base/', include('Emp_profile.urls', namespace='Emp_profile')),
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/',auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

Emp_profile/urls.py
from django.urls import path
from . import views 

app_name = 'Emp_profile'

urlpatterns=[
    path('',views.base, name='base'),
    path('Emp_list/',views.Emp_list,name='Emp_list'),
    path('Emp_list/detail/<int:employee_id>/',views.Emp_detail,name='Emp_detail'),
    path('update/<int:employee_id>', views.update, name="update"),  
    path('delete/<int:employee_id>', views.delete, name="delete"),
    path('Emp_form/',views.Emp_form, name='Emp_Form'),
    path('apply_for_leave/',views.Emp_leaveform, name='apply_for_leave'),
    path('leave_list/', views.Leave_list, name='leave_list'),
    path('approve_leave/<int:employee_id>', views.approve_leave, name='approve_leave'),
    path('deny_leave/<int:employee_id>', views.deny_leave, name='deny_leave'),
    path('approved_leave_list/',views.approved_leave_list, name='approved_leave_list'),
    path('denied_leave_list/', views.denied_leave_list, name='dined_leave_list'),

]

signup/urls.py
from django.urls import path
from .views import home,login_request,logout_request

app_name='signup'

urlpatterns=[
    path('',home,name='home'),
    path('login/',login_request, name='login'),
    path('base/logout/',logout_request,name='logout'),
    path('accounts/login/',login_request, name='login'),

    ]

Emp_profile/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

class Employee(AbstractUser):
    is_manager = models.BooleanField(default=False,blank=True)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    employee_id = models.CharField(unique=True,max_length=6,null=False)
    department = models.CharField(max_length=25, null=False)
    job_title = models.CharField(max_length=25, null=False)
    doj = models.DateField(null=True)
    TYPE_CHOICES = (
        ('part-time', 'Part-time'),
        ('full-time', 'Full-time'),
    )
    employment_type = models.CharField(max_length=10,
                                         choices=TYPE_CHOICES,
                                         default='full-time')
    salary = models.CharField(max_length=10)
    address = models.TextField(max_length=100, default="")
    mobile_number = models.CharField(max_length=10)
    dob = models.DateField(null=True)
    city = models.CharField(max_length=25, null=True)
    pin_code = models.CharField(max_length=25, null=True)
    state = models.CharField(max_length=25, null=True)

    GENDER_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
    )

    gender = models.CharField(max_length=10,
                              choices=GENDER_CHOICES,
                              default='male')
    MS_CHOICES = (
        ('married', 'Married'),
        ('unmarried', 'Unmarried'),
    )
    marrital_status = models.CharField(max_length=10,
                                       choices=MS_CHOICES,
                                       default='married')
    hobbies = models.CharField(max_length=25, null=True)

    def get_absolute_url(self):
        return reverse("Emp_profile:Emp_detail", args=[self.employee_id])

    def __str__(self):
        return self.first_name

class Leave(models.Model):
    TYPE_CHOISE = (
        ('Casual Leave(CL)','Casual Leave(CL)'),
        ('Sick Leave (SL)','Sick Leave (SL)'),
        ('Maternity Leave (ML)','Maternity Leave (ML)'),
        ('Paternity Leave','Paternity Leave'),
        ('Marriage Leave','Marriage Leave'),
    )

    email = models.EmailField(max_length=30,default="")
    employee_id = models.CharField(unique=True,max_length=6,default="")
    type_of_leave = models.CharField(choices=TYPE_CHOISE,default="", max_length=20)
    days_of_leave = models.PositiveIntegerField()
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    is_approved = models.BooleanField(default="", blank= True, null=True)

Emp_profile/forms.py
from django import forms
from .models import Employee, Leave


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'
        exclude = ['user', 'last_login', 'is_superuser', 'groups', 'user_permissions', 'is_staff', 'is_active',
                   'date_joined']

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(ProfileForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class LeaveForm(forms.ModelForm):
    class Meta:
        model = Leave
        fields = '__all__'
        exclude = ['is_approved']


class LeaveApprovalForm(forms.ModelForm):
    class Meta:
        model = Leave
        fields = '__all__'

Emp_profile/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password, check_password
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from .forms import ProfileForm, LeaveForm
from .models import Employee, Leave
from .decorators import manager_required
from EMS.settings import EMAIL_HOST_USER


@login_required
def base(request):
    user = request.user
    return render(request, 'Emp_profile/base.html', {'user': user})


@manager_required
def Emp_form(request):
    if request.method == "POST":
        form = ProfileForm(request.POST)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect('/base/')

    else:
        form = ProfileForm()
    return render(request, "Emp_profile/Emp_Form.html", {'form': form})


@login_required
def Emp_list(request):
    emp = Employee.objects.filter(is_superuser=False)
    return render(request, "Emp_profile/Emp_list.html", {'employee': emp})


@login_required
def Emp_detail(request, employee_id):
    obj = get_object_or_404(Employee, employee_id=employee_id)
    return render(request, 'Emp_profile/Emp_detail.html', {'obj': obj})


@manager_required
def update(request, employee_id):
    emp = get_object_or_404(Employee, employee_id=employee_id)
    form = ProfileForm(request.POST or None, instance=emp)
    if request.method == 'POST':

        if form.is_valid():
            form.save()
            return redirect('/base/Emp_list')
    else:
        pass
    return render(request, "Emp_profile/Emp_Form.html", {'form': form})


@manager_required
def delete(request, employee_id):
    emp = Employee.objects.get(employee_id=employee_id)
    emp.delete()
    return redirect("/base/")


@login_required
def Emp_leaveform(request):
    if request.method == "POST":
        form = LeaveForm(request.POST)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect('/base/')
    else:
        form = LeaveForm()
    return render(request, "Emp_leaveform.html", {'form': form})


@manager_required
def Leave_list(request):
    leave = Leave.objects.filter(is_approved__isnull=True)
    return render(request, "Leave_list.html", {'leave': leave})


@manager_required
def approve_leave(request, employee_id):
    leave = get_object_or_404(Leave, employee_id=employee_id)
    leave.is_approved = True
    leave.save()
    print(leave)
    to = get_object_or_404(Leave, employee_id=employee_id)
    print(to.email)
    subject = 'Regarding to your leave application'
    message = 'Your Leave has been approved by the management...'
    recepient = to.email
    send_mail(subject, message, EMAIL_HOST_USER, [recepient], fail_silently=False)
    return render(request, "Emp_profile/base.html")


@manager_required
def deny_leave(request, employee_id):
    leave = get_object_or_404(Leave, employee_id=employee_id)
    leave.is_approved = False
    leave.save()
    print(leave)
    to = get_object_or_404(Leave, employee_id=employee_id)
    print(to.email)
    subject = 'Regarding to your leave application'
    message = 'Your Leave has been Denied by the management...'
    recepient = to.email
    send_mail(subject, message, EMAIL_HOST_USER, [recepient], fail_silently=False)
    return render(request, "Emp_profile/base.html")


@manager_required
def approved_leave_list(request):
    leave = Leave.objects.filter(is_approved=True)
    return render(request, "approved_leave_list.html", {'leave': leave})


@manager_required
def denied_leave_list(request):
    leave = Leave.objects.filter(is_approved=False)
    return render(request, "denied_leave_list.html", {'leave': leave})

Emp_profile/templates/Emp_profile/Emp_Form.html
{% extends 'Emp_profile/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br><br><br><br>
<div class="container">
    <div class="carousel-item active">
        <div class="carousel-container">
            <form class="animate__animated animate__fadeInDown" method="post" novalidate>

                {% csrf_token %}
                <h1>Employee Profile Form</h1><br>
                <!--    {{ form|crispy }}-->
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{form.username|as_crispy_field}}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{form.email|as_crispy_field}}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{form.password|as_crispy_field}}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{form.is_manager|as_crispy_field}}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{form.first_name|as_crispy_field}}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{form.last_name|as_crispy_field}}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{form.employee_id|as_crispy_field}}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{form.department|as_crispy_field}}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{form.job_title|as_crispy_field}}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{form.doj|as_crispy_field}}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{form.employment_type|as_crispy_field}}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{form.salary|as_crispy_field}}
                    </div>
                </div>
                {{ form.address|as_crispy_field }}

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{form.mobile_number|as_crispy_field}}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{form.pin_code|as_crispy_field}}
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{form.city|as_crispy_field}}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{form.state|as_crispy_field}}
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{form.dob|as_crispy_field}}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{form.gender|as_crispy_field}}
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{form.marrital_status|as_crispy_field}}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{form.hobbies|as_crispy_field}}
                    </div>
                </div>

                <button type="submit" class="btn btn-success">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

Emp_profile/templates/Emp_profile/Emp_detail.html
{% extends 'Emp_profile/base.html' %}

{% block content %}
<br><br><br><br>
<div class="container">
    <div class="carousel-item active">
        <div class="carousel-container">
            <div class="animate__animated animate__fadeInDown">
                <h2>{{obj.first_name}} {{obj.last_name}}'s Details</h2>
                <br>
                <br>
                Name : {{ obj.first_name }} {{obj.last_name}}
                <hr>
                Employee Id : {{ obj.employee_id}}
                <hr>
                Email Id : {{ obj.email}}
                <hr>
                Department : {{obj.department}}
                <hr>
                Job title : {{obj.job_title}}
                <hr>
                Date of join : {{obj.doj}}
                <hr>
                Employeement Types : {{obj.employeement_type}}
                <hr>
                Address : {{obj.address}}
                <hr>
                City : {{ obj.city}}
                <hr>
                Pin Code : {{obj.pin_code}}
                <hr>
                Contact Number : {{obj.mobile_number}}
                <hr>
                State : {{obj.state}}
                <hr>
                Gender : {{obj.gender}}
                <hr>
                Hobbies : {{obj.hobbies}}
                Date of Birth : {{obj.dob}}
                <hr>
                Marrital status : {{obj.marrital_status}}
                <hr>
            </div>

        </div>
    </div>
</div>
{% endblock content %}

Emp_profile/templates/Emp_profile/Emp_list.html
{% extends 'Emp_profile/base.html'%}
{% block content %}
<br><br><br><br>
<div class="container">
    <div class="carousel-item active">
        <div class="carousel-container">
            <div class="animate__animated animate__fadeInDown">
                <h2>Employee List</h2>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Employee Id</th>
                        <th scope="col">Date of Join</th>
                        <th scope="col">Salary</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for emp in employee %}
                    <tr>

                        <td><a href='{{ emp.get_absolute_url }}'>
                            {{ emp.first_name }} {{ emp.last_name}}
                        </a>
                        </td>
                        <td scope="row">{{emp.employee_id}}</td>
                        <td>
                            <p class="date">
                                Joined at {{ emp.doj }}
                            </p>
                        </td>
                        <td scope="row">
                            {{emp.salary}}
                        </td>
                        <td>
                            <button type="button" class="btn btn-default" aria-label="Left Align">
                                <span class="glyphicon glyphicon-align-left" aria-hidden="true"><a
                                        href="{% url 'Emp_profile:update' emp.employee_id %}">Edit</a></span>
                            </button>
                            <button type="button" class="btn btn-default" aria-label="Left Align">
                                <span class="glyphicon glyphicon-align-left" aria-hidden="true"><a
                                        href="{% url 'Emp_profile:delete' emp.employee_id %}">Delete</a></span>
                            </button>
                        </td>
                    </tr>
                    {% endfor%}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock %}

Emp_profile/templates/Emp_profile/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Slick-Services - EMS</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/logo.png' %}" rel="icon">

    <!-- Google Fonts -->
    <link href="{% static 'https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i' %}"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/line-awesome/css/line-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Selecao - v2.3.1
    * Template URL: https://bootstrapmade.com/selecao-bootstrap-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>
<!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center ">
    <div class="container d-flex align-items-center">
        <div class="logo mr-auto">
            <h1 class="text-light"><a href="{% url 'Emp_profile:base' %}">Slick-Services</a></h1>
        </div>

        <nav class="nav-menu d-none d-lg-block">
            <ul>
                <li><a href="{% url 'Emp_profile:base' %}">Home</a></li>
                <li><a href="{% url 'Emp_profile:Emp_list'%}">Employee List</a></li>
                <li><a href="{% url 'Emp_profile:Emp_Form'%}">Add New Employee</a></li>
                <li><a href="{% url 'Emp_profile:apply_for_leave'%}">Apply for Leave</a></li>
                <li><a href="{% url 'Emp_profile:leave_list' %}">Approve Leave</a></li>
                <li><a href="{% url 'signup:logout' %}">Log-Out</a></li>
            </ul>
        </nav><!-- .nav-menu -->
    </div>
</header>
<!-- End Header -->
{% block content %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-end align-items-center">
    <div id="heroCarousel" class="container carousel carousel-fade" data-ride="carousel">
        <!-- Slide 1 -->
        <div class="carousel-item active">
            <div class="carousel-container">
                <h2 class="animate__animated animate__fadeInDown">Welcome to <span>Slick-Services</span></h2>
                <p class="animate__animated animate__fadeInDown">We're In The Business Of Helping You Manage your Sample and Panel.</p>
            </div>
        </div>
    </div>

    <svg class="hero-waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
         viewBox="0 24 150 28 " preserveAspectRatio="none">
        <defs>
            <path id="wave-path" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z">
        </defs>
        <g class="wave1">
            <use xlink:href="#wave-path" x="50" y="3" fill="rgba(255,255,255, .1)">
        </g>
        <g class="wave2">
            <use xlink:href="#wave-path" x="50" y="0" fill="rgba(255,255,255, .2)">
        </g>
        <g class="wave3">
            <use xlink:href="#wave-path" x="50" y="9" fill="#fff">
        </g>
    </svg>


    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    {% endblock %}
</body>

</html>