EMS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('signup.urls', namespace='signup')),
    path('base/', include('Emp_profile.urls', namespace='Emp_profile')),
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/',auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

Emp_profile/urls.py
from django.urls import path
from . import views 

app_name = 'Emp_profile'

urlpatterns=[
    path('',views.base, name='base'),
    path('Emp_list/',views.Emp_list,name='Emp_list'),
    path('Emp_list/detail/<int:employee_id>/',views.Emp_detail,name='Emp_detail'),
    path('update/<int:employee_id>', views.update, name="update"),  
    path('delete/<int:employee_id>', views.delete, name="delete"),
    path('Emp_form/',views.Emp_form, name='Emp_Form'),
    path('apply_for_leave/',views.Emp_leaveform, name='apply_for_leave'),
    path('leave_list/', views.Leave_list, name='leave_list'),
    path('approve_leave/<int:employee_id>', views.approve_leave, name='approve_leave'),
    path('deny_leave/<int:employee_id>', views.deny_leave, name='deny_leave'),
    path('approved_leave_list/',views.approved_leave_list, name='approved_leave_list'),
    path('denied_leave_list/', views.denied_leave_list, name='dined_leave_list'),

]

Emp_profile/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

class Employee(AbstractUser):
    is_manager = models.BooleanField(default=False,blank=True)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    employee_id = models.CharField(unique=True,max_length=6,null=False)
    department = models.CharField(max_length=25, null=False)
    job_title = models.CharField(max_length=25, null=False)
    doj = models.DateField(null=True)
    TYPE_CHOICES = (
        ('part-time', 'Part-time'),
        ('full-time', 'Full-time'),
    )
    employment_type = models.CharField(max_length=10,
                                         choices=TYPE_CHOICES,
                                         default='full-time')
    salary = models.CharField(max_length=10)
    address = models.TextField(max_length=100, default="")
    mobile_number = models.CharField(max_length=10)
    dob = models.DateField(null=True)
    city = models.CharField(max_length=25, null=True)
    pin_code = models.CharField(max_length=25, null=True)
    state = models.CharField(max_length=25, null=True)

    GENDER_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
    )

    gender = models.CharField(max_length=10,
                              choices=GENDER_CHOICES,
                              default='male')
    MS_CHOICES = (
        ('married', 'Married'),
        ('unmarried', 'Unmarried'),
    )
    marrital_status = models.CharField(max_length=10,
                                       choices=MS_CHOICES,
                                       default='married')
    hobbies = models.CharField(max_length=25, null=True)

    def get_absolute_url(self):
        return reverse("Emp_profile:Emp_detail", args=[self.employee_id])

    def __str__(self):
        return self.first_name

class Leave(models.Model):
    TYPE_CHOISE = (
        ('Casual Leave(CL)','Casual Leave(CL)'),
        ('Sick Leave (SL)','Sick Leave (SL)'),
        ('Maternity Leave (ML)','Maternity Leave (ML)'),
        ('Paternity Leave','Paternity Leave'),
        ('Marriage Leave','Marriage Leave'),
    )

    email = models.EmailField(max_length=30,default="")
    employee_id = models.CharField(unique=True,max_length=6,default="")
    type_of_leave = models.CharField(choices=TYPE_CHOISE,default="", max_length=20)
    days_of_leave = models.PositiveIntegerField()
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    is_approved = models.BooleanField(default="", blank= True, null=True)

Emp_profile/forms.py
from django import forms
from .models import Employee, Leave


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'
        exclude = ['user', 'last_login', 'is_superuser', 'groups', 'user_permissions', 'is_staff', 'is_active',
                   'date_joined']

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(ProfileForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class LeaveForm(forms.ModelForm):
    class Meta:
        model = Leave
        fields = '__all__'
        exclude = ['is_approved']


class LeaveApprovalForm(forms.ModelForm):
    class Meta:
        model = Leave
        fields = '__all__'

Emp_profile/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password, check_password
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from .forms import ProfileForm, LeaveForm
from .models import Employee, Leave
from .decorators import manager_required
from EMS.settings import EMAIL_HOST_USER


@login_required
def base(request):
    user = request.user
    return render(request, 'Emp_profile/base.html', {'user': user})


@manager_required
def Emp_form(request):
    if request.method == "POST":
        form = ProfileForm(request.POST)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect('/base/')

    else:
        form = ProfileForm()
    return render(request, "Emp_profile/Emp_Form.html", {'form': form})


@login_required
def Emp_list(request):
    emp = Employee.objects.filter(is_superuser=False)
    return render(request, "Emp_profile/Emp_list.html", {'employee': emp})


@login_required
def Emp_detail(request, employee_id):
    obj = get_object_or_404(Employee, employee_id=employee_id)
    return render(request, 'Emp_profile/Emp_detail.html', {'obj': obj})


@manager_required
def update(request, employee_id):
    emp = get_object_or_404(Employee, employee_id=employee_id)
    form = ProfileForm(request.POST or None, instance=emp)
    if request.method == 'POST':

        if form.is_valid():
            form.save()
            return redirect('/base/Emp_list')
    else:
        pass
    return render(request, "Emp_profile/Emp_Form.html", {'form': form})


@manager_required
def delete(request, employee_id):
    emp = Employee.objects.get(employee_id=employee_id)
    emp.delete()
    return redirect("/base/")


@login_required
def Emp_leaveform(request):
    if request.method == "POST":
        form = LeaveForm(request.POST)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect('/base/')
    else:
        form = LeaveForm()
    return render(request, "Emp_leaveform.html", {'form': form})


@manager_required
def Leave_list(request):
    leave = Leave.objects.filter(is_approved__isnull=True)
    return render(request, "Leave_list.html", {'leave': leave})


@manager_required
def approve_leave(request, employee_id):
    leave = get_object_or_404(Leave, employee_id=employee_id)
    leave.is_approved = True
    leave.save()
    print(leave)
    to = get_object_or_404(Leave, employee_id=employee_id)
    print(to.email)
    subject = 'Regarding to your leave application'
    message = 'Your Leave has been approved by the management...'
    recepient = to.email
    send_mail(subject, message, EMAIL_HOST_USER, [recepient], fail_silently=False)
    return render(request, "Emp_profile/base.html")


@manager_required
def deny_leave(request, employee_id):
    leave = get_object_or_404(Leave, employee_id=employee_id)
    leave.is_approved = False
    leave.save()
    print(leave)
    to = get_object_or_404(Leave, employee_id=employee_id)
    print(to.email)
    subject = 'Regarding to your leave application'
    message = 'Your Leave has been Denied by the management...'
    recepient = to.email
    send_mail(subject, message, EMAIL_HOST_USER, [recepient], fail_silently=False)
    return render(request, "Emp_profile/base.html")


@manager_required
def approved_leave_list(request):
    leave = Leave.objects.filter(is_approved=True)
    return render(request, "approved_leave_list.html", {'leave': leave})


@manager_required
def denied_leave_list(request):
    leave = Leave.objects.filter(is_approved=False)
    return render(request, "denied_leave_list.html", {'leave': leave})

Emp_profile/templates/Emp_leaveform.html
{% extends 'Emp_profile/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br><br><br><br>
<div class="container">
    <div class="carousel-item active">
        <div class="carousel-container">
            <form class="animate__animated animate__fadeInDown" method="post" novalidate>

                <h1>Fill your Leave form</h1>
                <form method="POST" novalidate>
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-5 mb-4">
                            {{form.email|as_crispy_field}}
                        </div>
                        <div class="form-group col-md-5 mb-0">
                            {{form.employee_id|as_crispy_field}}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-5 mb-4">
                            {{form.type_of_leave|as_crispy_field}}
                        </div>
                        <div class="form-group col-md-5 mb-0">
                            {{form.days_of_leave|as_crispy_field}}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-5 mb-4">
                            {{form.start_date|as_crispy_field}}
                        </div>
                        <div class="form-group col-md-5 mb-0">
                            {{form.end_date|as_crispy_field}}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-success">Submit</button>
                </form>
        </div>
    </div>
</div>
{% endblock %}

Emp_profile/templates/Leave_list.html
{% extends 'Emp_profile/base.html'%}
{% block content %}
<br><br><br><br>
<div class="container">
    <div class="carousel-item active">
        <div class="carousel-container">
            <div class="animate__animated animate__fadeInDown">
                <h2>Leave List</h2>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Employee Id</th>
                        <th scope="col">Leave Type</th>
                        <th scope="col">Days of leave</th>
                        <th scope="col">Start Date</th>
                        <th scope="col">End Date</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for emp in leave %}
                    <tr>

                        <td>{{ emp.employee_id }}</td>
                        <td>{{emp.type_of_leave}}</td>
                        <td>
                            <p class="date">
                                For {{ emp.days_of_leave }} Days
                            </p>
                        </td>
                        <td scope="row">
                            {{emp.start_date}}
                        </td>
                        <td scope="row">
                            {{emp.end_date}}
                        </td>

                        <td>
                            <a href="{% url 'Emp_profile:approve_leave' emp.employee_id %}">Approve</a>
                        </td>
                        <td>
                            <a href="{% url 'Emp_profile:deny_leave' emp.employee_id %}">Deny</a>
                        </td>

                    </tr>
                    {% endfor%}
                    </tbody>
                </table>
                <div align="center">
                    <a href="{% url 'Emp_profile:approved_leave_list' %}">Approved Leave List</a><br>
                    <a href="{% url 'Emp_profile:dined_leave_list' %}">Dined Leave List</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Emp_profile/templates/approved_leave_list.html
{% extends 'Emp_profile/base.html'%}
{% block content %}
<br><br><br><br>
<div class="container">
    <div class="carousel-item active">
        <div class="carousel-container">
            <div class="animate__animated animate__fadeInDown">
                <h2>Approve Leave List</h2>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Employee Id</th>
                        <th scope="col">Leave Type</th>
                        <th scope="col">Days of leave</th>
                        <th scope="col">Start Date</th>
                        <th scope="col">End Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for emp in leave %}
                    <tr>

                        <td>{{ emp.employee_id }}</td>
                        <td scope="row">{{emp.type_of_leave}}</td>
                        <td>
                            <p class="date">
                                For {{ emp.days_of_leave }} Days
                            </p>
                        </td>
                        <td scope="row">
                            {{emp.start_date}}
                        </td>
                        <td scope="row">
                            {{emp.end_date}}
                        </td>

                    </tr>
                    {% endfor%}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Emp_profile/templates/denied_leave_list.html
{% extends 'Emp_profile/base.html'%}
{% block content %}
<br><br><br><br>
<div class="container">
    <div class="carousel-item active">
        <div class="carousel-container">
            <div class="animate__animated animate__fadeInDown">
                <h2>Denied Leave List</h2>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Employee Id</th>
                        <th scope="col">Leave Type</th>
                        <th scope="col">Days of leave</th>
                        <th scope="col">Start Date</th>
                        <th scope="col">End Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for emp in leave %}
                    <tr>

                        <td>{{ emp.employee_id }}</td>
                        <td scope="row">{{emp.type_of_leave}}</td>
                        <td>
                            <p class="date">
                                For {{ emp.days_of_leave }} Days
                            </p>
                        </td>
                        <td scope="row">
                            {{emp.start_date}}
                        </td>
                        <td scope="row">
                            {{emp.end_date}}
                        </td>
                    </tr>
                    {% endfor%}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}